# The deploy configuration contains all resources of the app in simple configuration files which can be deployed through
# the following command:
# > php bin/fusio deploy
# Through this you can store your complete app configuration in simple configuration files under GIT and reproduce your
# Fusio configuration on deployment. The deployment then calls also the internal API to create these resources. To see
# an example howto use the deployment please take a look at our repository: https://github.com/apioo/fusio-sample-cms

config: !include resources/config.yaml
connection: !include resources/connection.yaml
event: !include resources/event.yaml
operation: !include resources/operation.yaml
plan: !include resources/plan.yaml
role: !include resources/role.yaml
scope: !include resources/scope.yaml
